name: Push to GitLab

on:
  push:
    branches:
      - '**'  # run on any push
  workflow_dispatch:      # allows manual trigger

jobs:
  push_to_gitlab:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full clone for --mirror

      - name: Set up Git
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "bot@example.com"
        shell: pwsh

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Remove existing remote if it exists
          if (git remote get-url gitlab -ErrorAction SilentlyContinue) {
              git remote remove gitlab
          }

          # Add GitLab remote using PAT (quote to handle special characters)
          $gitUrl = "https://oauth2:${env:GITLAB_TOKEN}@gitlab.com/Maruch-MrSky/c05_mrskoc-marek.git"
          git remote add gitlab $gitUrl

          # Push all branches, tags, and refs
          git push --mirror gitlab --verbose
        shell: pwsh

