name: Push to GitLab

# Allow manual trigger
on:
  workflow_dispatch:

jobs:
  push_to_gitlab:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for --mirror push

      - name: Set up Git
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "bot@example.com"
        shell: pwsh

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          try {
              git remote remove gitlab
          } catch {
              Write-Host "Remote 'gitlab' does not exist, continuing..."
          }

          git remote add gitlab https://oauth2:${env:GITLAB_TOKEN}@gitlab.com/Maruch-MrSky/c05_mrskoc-marek.git
          git push --mirror gitlab --verbose
        shell: pwsh
