- uses: actions/checkout@v4
  with:
    fetch-depth: 0

- name: Push to GitLab
  env:
    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
  run: |
    git config --global user.name "github-bot"
    git config --global user.email "bot@example.com"
    git remote remove gitlab || true
    git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/Maruch-MrSky/c05_mrskoc-marek.git
    git push --mirror gitlab --verbose
