name: Gitlab Mirror

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch:   # allows manual trigger

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Maruch-MrSky/c05_mrskoc_marek.git

      - name: Push to GitLab
        run: |
          git push gitlab main --force
